language: groovy
jdk:
- openjdk8
sudo: false
branches:
  only:
  - develop
  - master
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - JAVA_TOOL_OPTIONS=-Dhttps.protocols=TLSv1.2
  - secure: BQq6EWYmJDI9+AU62kqe9ZdjWN5tWgIuKCCoaXJMGs0JudEUxRw2ziZ1GWPgVK8UscFGO50ZJnN3Ql7fP9BIr5JioqH3MprSY9dvmDS5ChBap8viYii4MxVa9eYL6lR4piyg8UGaqrpbugDrcwyd6WIGpuKdj0ZGraBE5syUaQvd9xN72oYKGakp4IsVH8DoGYiTISGg7dnAG3NgaSPWlUDjZhAKcXbZMyveQIazM5AT+/2Pvc5tZTDDJC75Xadtsoeb+azA3LTLJSNh1FLoMWfT0KDNZcuyqa1mBAAedrdoYr8JvpZOJPBNdxFafvh99hM2Wo43Azuf1UfPehLIaXhSAzF/hGEvOGROZvpmDdG5R0OTXLcNjDIR9kEIThBrhev9/0bDrtb5yhpzfx5lLhlzMJVx5NrUkNXj/loRq9gs2GO1RMxLrHkdsnC2gOOuDaS1wPUL4YVnc2unkyZNaQNHYLs/V8BO+J6JiOnNFtbuWrMpno0O9r+x6Z7NQvIgOwrqdfLkk0rSlG0DQuLHt4sej/QMwtfXqZAz5/cXvdJuUVNQzk8snHcP3CkS7Si2QN/8d3Da5P0t5xiJ8SPNqrAZu0dnnNdyOWLL6Be6sxaV3n/U92SwuUv5yxORs7evP3LC0myuUmn8v40mtxYEDJ8aNWvdo/wrj4TMEIZWoX8=
  - secure: JEX8hLDQZVNIPd5KdWuBI4KQ1ZF+qit6xoSM5wi9TXpRX+V6zbFJ1KZvR2htIbJbKDVL6giiOAjOXpyEnKT5UI7jqWCXQcV20+VTkyuxkrXe2CrBbSfkWdU0FPjirVb2dEPxSqH7TNB73gnsKl2FvFs/oGx2LGx9maKl7SVTRwMGG7/GhzSKDwFsXnCYWcLAIAk0/6bSorcMzOtEDgYGkdBYLP3PxHpKpBw+ecm7AHdDwRGrX5oh4ZOuNxe4HBVKzZRH/jDAaMPgAWvUQ3fbSpxLjIPnkE6euDupP3tJBZEsGUE1YvaKZuRwMZAx5UdLZLHER8MzWTlhwcbrEqfS+GJhbnmq+hCSfP7UFZ2Pfii2/6AysFaM0CgM/d7q6o0u7sBSNiH7IDzV0lHd3d6nA/bhmjeyUQf1Nb+yZMmvmIOl5pijrWKs9i45+nVwzHOol5u3lh2WNe0CPNhq/xBQMQvuC8ad6NfSsjq8GY3Z2keU0feywJNDq9AkZQwwdCIMsdpKvldeB9kx73v+RjIuO/OTElwrDSSwaqGo3rHembrW1bQLG4O/zF5ZOdHK9ZAXvijZO7w31VfEzsmEDekQDwOBcpDzP6B81vXZIQUA5QtMfrlrL54heSba4EJ2fr/5HlKEFX39IzVsqLa5s8M/cjlrxPdc706+Itz2DOPPvUU=
