buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
        mavenCentral()
    }
    dependencies {
        classpath "org.apache.grails:grails-gradle-plugins:$grailsVersion"
        classpath "org.springframework.boot:spring-boot-gradle-plugin:3.3.5"
    }
}

plugins {
    id "groovy"
    id 'maven-publish'
}

version "2.0.0-SNAPSHOT"
group "au.org.ala.plugins"

apply plugin: "org.apache.grails.gradle.grails-plugin"
apply plugin: "org.apache.grails.gradle.grails-gsp"
apply plugin: "eclipse"
apply plugin: "idea"

repositories {
    maven { url "https://repo.grails.org/grails/core" }
    mavenCentral()
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    implementation platform("org.apache.grails:grails-bom:$grailsVersion")

    implementation "org.apache.groovy:groovy"
    implementation "org.apache.grails:grails-core"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-url-mappings"

    developmentOnly "org.springframework.boot:spring-boot-devtools"

    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"

    // Swagger (OK but should be consistent version-managed)
    implementation 'io.swagger.core.v3:swagger-core:2.2.23'
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.23'
    implementation 'io.swagger.core.v3:swagger-models:2.2.23'
    implementation 'io.swagger.core.v3:swagger-integration:2.2.23'
    implementation("io.swagger.core.v3:swagger-jaxrs2-jakarta:2.2.23")

    implementation 'jakarta.ws.rs:jakarta.ws.rs-api:3.0.0'
    implementation "org.webjars:swagger-ui:4.5.2"

    testImplementation "org.mockito:mockito-core"
    testImplementation "org.apache.grails:grails-testing-support-web"
}

bootRun {
    ignoreExitValue true
    jvmArgs(
        '-Dspring.output.ansi.enabled=always',
        '-Xmx1024m')
    sourceResources sourceSets.main
    String springProfilesActive = 'spring.profiles.active'
    systemProperty springProfilesActive, System.getProperty(springProfilesActive)
}

tasks.withType(GroovyCompile) {
    configure(groovyOptions) {
        forkOptions.jvmArgs = ['-Xmx1024m']
    }
}

// enable if you wish to package this plugin as a standalone application
bootJar.enabled = false

publishing {
    repositories {
        maven {
            name 'Nexus'
            url "https://nexus.ala.org.au/content/repositories/${project.version.endsWith('-SNAPSHOT') ? 'snapshots' : 'releases'}"
            credentials {
                username = System.getenv('TRAVIS_DEPLOY_USERNAME')
                password = System.getenv('TRAVIS_DEPLOY_PASSWORD')
            }
        }
    }
    publications {
        maven(MavenPublication) {
            from components.java

            pom {
                name = 'OpenAPI Plugin'
                description = 'OpenAPI support for ALA Apps'
                url = 'https://github.com/AtlasOfLivingAustralia/openapi-plugin'
                licenses {
                    license {
                        name = 'MPL-1.1'
                        url = 'https://www.mozilla.org/en-US/MPL/1.1/'
                    }
                }
                developers {
                    developer {
                        id = 'sbearcsiro'
                        name = 'Simon Bear'
                        email = 'simon.bear@csiro.au'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/AtlasOfLivingAustralia/openapi-plugin.git'
                    developerConnection = 'scm:git:ssh://github.com:AtlasOfLivingAustralia/openapi-plugin.git'
                    url = 'https://github.com/AtlasOfLivingAustralia/openapi-plugin/tree/main'
                }
            }

        }
    }
}
